/* src/components/typography/Text.svelte generated by Svelte v3.30.1 */
import { SvelteComponent, init, safe_not_equal } from "../../../web_modules/svelte/internal.js";

class Text extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Text;