/* demo/views/Example.svx generated by Svelte v3.31.0 */
import {
	SvelteComponent,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	noop,
	safe_not_equal,
	space,
	text,
	transition_in,
	transition_out
} from "../web_modules/svelte/internal.js";

import { AntdSvelte } from "../index.js";

function create_default_slot(ctx) {
	let t;

	return {
		c() {
			t = text(title);
		},
		m(target, anchor) {
			insert(target, t, anchor);
		},
		p: noop,
		d(detaching) {
			if (detaching) detach(t);
		}
	};
}

function create_fragment(ctx) {
	let title_1;
	let t0;
	let p0;
	let t2;
	let p1;
	let t4;
	let p2;
	let t6;
	let p3;
	let current;

	title_1 = new /*Title*/ ctx[0]({
			props: {
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			}
		});

	return {
		c() {
			create_component(title_1.$$.fragment);
			t0 = space();
			p0 = element("p");
			p0.textContent = "Eu reprehenderit consectetur eu consequat qui pariatur nisi tempor id. Nisi ullamco laboris reprehenderit ex veniam. Ad tempor cupidatat pariatur officia eiusmod magna voluptate ea occaecat et excepteur. Eu duis Lorem in ipsum dolor consectetur fugiat laboris. Dolore eu eu dolore deserunt. Nisi laborum consequat excepteur consequat cupidatat cupidatat aliqua exercitation.";
			t2 = space();
			p1 = element("p");
			p1.textContent = "Quis cupidatat excepteur elit culpa voluptate mollit esse. Enim ea magna mollit incididunt eu exercitation est anim consectetur quis aliquip ipsum mollit. Laborum tempor mollit consequat id consequat officia consequat dolor consequat non.";
			t4 = space();
			p2 = element("p");
			p2.textContent = "Eu reprehenderit consectetur eu consequat qui pariatur nisi tempor id. Nisi ullamco laboris reprehenderit ex veniam. Ad tempor cupidatat pariatur officia eiusmod magna voluptate ea occaecat et excepteur. Eu duis Lorem in ipsum dolor consectetur fugiat laboris. Dolore eu eu dolore deserunt. Nisi laborum consequat excepteur consequat cupidatat cupidatat aliqua exercitation.";
			t6 = space();
			p3 = element("p");
			p3.textContent = "Quis cupidatat excepteur elit culpa voluptate mollit esse. Enim ea magna mollit incididunt eu exercitation est anim consectetur quis aliquip ipsum mollit. Laborum tempor mollit consequat id consequat officia consequat dolor consequat non.";
		},
		m(target, anchor) {
			mount_component(title_1, target, anchor);
			insert(target, t0, anchor);
			insert(target, p0, anchor);
			insert(target, t2, anchor);
			insert(target, p1, anchor);
			insert(target, t4, anchor);
			insert(target, p2, anchor);
			insert(target, t6, anchor);
			insert(target, p3, anchor);
			current = true;
		},
		p(ctx, [dirty]) {
			const title_1_changes = {};

			if (dirty & /*$$scope*/ 2) {
				title_1_changes.$$scope = { dirty, ctx };
			}

			title_1.$set(title_1_changes);
		},
		i(local) {
			if (current) return;
			transition_in(title_1.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(title_1.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(title_1, detaching);
			if (detaching) detach(t0);
			if (detaching) detach(p0);
			if (detaching) detach(t2);
			if (detaching) detach(p1);
			if (detaching) detach(t4);
			if (detaching) detach(p2);
			if (detaching) detach(t6);
			if (detaching) detach(p3);
		}
	};
}

const metadata = { "title": "Fabuloso" };
const { title } = metadata;

function instance($$self) {
	const { Title } = AntdSvelte;
	return [Title];
}

class Example extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Example;
export { metadata };