import './Welcome.css.proxy.js';
/* demo/views/Welcome.svx generated by Svelte v3.31.0 */
import {
	SvelteComponent,
	attr,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	safe_not_equal,
	space,
	text,
	transition_in,
	transition_out
} from "../web_modules/svelte/internal.js";

import { AntdSvelte } from "../index.js";

function create_default_slot(ctx) {
	let t;

	return {
		c() {
			t = text("Introduction");
		},
		m(target, anchor) {
			insert(target, t, anchor);
		},
		d(detaching) {
			if (detaching) detach(t);
		}
	};
}

function create_fragment(ctx) {
	let title;
	let t0;
	let div;
	let t1;
	let p0;
	let t3;
	let p1;
	let t5;
	let p2;
	let t7;
	let p3;
	let current;

	title = new /*Title*/ ctx[0]({
			props: {
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			}
		});

	return {
		c() {
			create_component(title.$$.fragment);
			t0 = space();
			div = element("div");
			div.innerHTML = `<img class="fusion svelte-zbobmt" src="./assets/banner.png"/>`;
			t1 = space();
			p0 = element("p");
			p0.textContent = "Eu reprehenderit consectetur eu consequat qui pariatur nisi tempor id. Nisi ullamco laboris reprehenderit ex veniam. Ad tempor cupidatat pariatur officia eiusmod magna voluptate ea occaecat et excepteur. Eu duis Lorem in ipsum dolor consectetur fugiat laboris. Dolore eu eu dolore deserunt. Nisi laborum consequat excepteur consequat cupidatat cupidatat aliqua exercitation.";
			t3 = space();
			p1 = element("p");
			p1.textContent = "Quis cupidatat excepteur elit culpa voluptate mollit esse. Enim ea magna mollit incididunt eu exercitation est anim consectetur quis aliquip ipsum mollit. Laborum tempor mollit consequat id consequat officia consequat dolor consequat non.";
			t5 = space();
			p2 = element("p");
			p2.textContent = "Eu reprehenderit consectetur eu consequat qui pariatur nisi tempor id. Nisi ullamco laboris reprehenderit ex veniam. Ad tempor cupidatat pariatur officia eiusmod magna voluptate ea occaecat et excepteur. Eu duis Lorem in ipsum dolor consectetur fugiat laboris. Dolore eu eu dolore deserunt. Nisi laborum consequat excepteur consequat cupidatat cupidatat aliqua exercitation.";
			t7 = space();
			p3 = element("p");
			p3.textContent = "Quis cupidatat excepteur elit culpa voluptate mollit esse. Enim ea magna mollit incididunt eu exercitation est anim consectetur quis aliquip ipsum mollit. Laborum tempor mollit consequat id consequat officia consequat dolor consequat non.";
			attr(div, "class", "fusion-container svelte-zbobmt");
		},
		m(target, anchor) {
			mount_component(title, target, anchor);
			insert(target, t0, anchor);
			insert(target, div, anchor);
			insert(target, t1, anchor);
			insert(target, p0, anchor);
			insert(target, t3, anchor);
			insert(target, p1, anchor);
			insert(target, t5, anchor);
			insert(target, p2, anchor);
			insert(target, t7, anchor);
			insert(target, p3, anchor);
			current = true;
		},
		p(ctx, [dirty]) {
			const title_changes = {};

			if (dirty & /*$$scope*/ 2) {
				title_changes.$$scope = { dirty, ctx };
			}

			title.$set(title_changes);
		},
		i(local) {
			if (current) return;
			transition_in(title.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(title.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(title, detaching);
			if (detaching) detach(t0);
			if (detaching) detach(div);
			if (detaching) detach(t1);
			if (detaching) detach(p0);
			if (detaching) detach(t3);
			if (detaching) detach(p1);
			if (detaching) detach(t5);
			if (detaching) detach(p2);
			if (detaching) detach(t7);
			if (detaching) detach(p3);
		}
	};
}

function instance($$self) {
	const { Title } = AntdSvelte;
	return [Title];
}

class Welcome extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Welcome;