/* demo/components/ReactWrapper.svelte generated by Svelte v3.31.0 */
import {
	SvelteComponent,
	assign,
	binding_callbacks,
	detach,
	element,
	exclude_internal_props,
	init,
	insert,
	noop,
	safe_not_equal
} from "../web_modules/svelte/internal.js";

import { afterUpdate, onDestroy } from "../web_modules/svelte.js";
import React from "https://cdn.skypack.dev/react";
import { render as ReactDOMrender, unmountComponentAtNode } from "https://cdn.skypack.dev/react-dom";

function create_fragment(ctx) {
	let div;

	return {
		c() {
			div = element("div");
		},
		m(target, anchor) {
			insert(target, div, anchor);
			/*div_binding*/ ctx[1](div);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
			/*div_binding*/ ctx[1](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	var __awaiter = this && this.__awaiter || function (thisArg, _arguments, P, generator) {
		function adopt(value) {
			return value instanceof P
			? value
			: new P(function (resolve) {
						resolve(value);
					});
		}

		return new (P || (P = Promise))(function (resolve, reject) {
				function fulfilled(value) {
					try {
						step(generator.next(value));
					} catch(e) {
						reject(e);
					}
				}

				function rejected(value) {
					try {
						step(generator["throw"](value));
					} catch(e) {
						reject(e);
					}
				}

				function step(result) {
					result.done
					? resolve(result.value)
					: adopt(result.value).then(fulfilled, rejected);
				}

				step((generator = generator.apply(thisArg, _arguments || [])).next());
			});
	};

	var __rest = this && this.__rest || function (s, e) {
		var t = {};
		for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0) t[p] = s[p];

		if (s != null && typeof Object.getOwnPropertySymbols === "function") for (var i = 0, p = Object.getOwnPropertySymbols(s); i < p.length; i++) {
			if (e.indexOf(p[i]) < 0 && Object.prototype.propertyIsEnumerable.call(s, p[i])) t[p[i]] = s[p[i]];
		}

		return t;
	};

	let container;

	afterUpdate(() => __awaiter(void 0, void 0, void 0, function* () {
		const { component, children } = $$props,
			props = __rest($$props, ["component", "children"]);

		ReactDOMrender(React.createElement(component, props, props.children), container);
	}));

	onDestroy(() => {
		unmountComponentAtNode(container);
	});

	function div_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			container = $$value;
			$$invalidate(0, container);
		});
	}

	$$self.$$set = $$new_props => {
		$$invalidate(4, $$props = assign(assign({}, $$props), exclude_internal_props($$new_props)));
	};

	$$props = exclude_internal_props($$props);
	return [container, div_binding];
}

class ReactWrapper extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default ReactWrapper;