/* src/components/Layout/Layout.svelte generated by Svelte v3.29.7 */
import {
	SvelteComponent,
	attr,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	toggle_class,
	transition_in,
	transition_out,
	update_slot
} from "../../../web_modules/svelte/internal.js";

function create_fragment(ctx) {
	let section;
	let current;
	const default_slot_template = /*#slots*/ ctx[5].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[4], null);

	return {
		c() {
			section = element("section");
			if (default_slot) default_slot.c();
			attr(section, "class", /*classes*/ ctx[2]);
			attr(section, "style", /*style*/ ctx[0]);
			toggle_class(section, "ant-layout-has-sider", /*hasSider*/ ctx[1]);
		},
		m(target, anchor) {
			insert(target, section, anchor);

			if (default_slot) {
				default_slot.m(section, null);
			}

			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 16) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[4], dirty, null, null);
				}
			}

			if (!current || dirty & /*classes*/ 4) {
				attr(section, "class", /*classes*/ ctx[2]);
			}

			if (!current || dirty & /*style*/ 1) {
				attr(section, "style", /*style*/ ctx[0]);
			}

			if (dirty & /*classes, hasSider*/ 6) {
				toggle_class(section, "ant-layout-has-sider", /*hasSider*/ ctx[1]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(section);
			if (default_slot) default_slot.d(detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let { style = undefined } = $$props;
	let { hasSider = false } = $$props;
	let { className = undefined } = $$props;

	$$self.$$set = $$props => {
		if ("style" in $$props) $$invalidate(0, style = $$props.style);
		if ("hasSider" in $$props) $$invalidate(1, hasSider = $$props.hasSider);
		if ("className" in $$props) $$invalidate(3, className = $$props.className);
		if ("$$scope" in $$props) $$invalidate(4, $$scope = $$props.$$scope);
	};

	let classes;

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*className*/ 8) {
			$: $$invalidate(2, classes = ["ant-layout", className ? className : false].filter(item => item).join(" "));
		}
	};

	return [style, hasSider, classes, className, $$scope, slots];
}

class Layout extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { style: 0, hasSider: 1, className: 3 });
	}
}

export default Layout;